### ISSUE TITLE
 four suggestions

### ISSUE THREAD

**Issue by hanjunqiang** [ray00178/EasyAlbum#1]
Hello, I have four suggestions.
1. When enlarging the picture browsing, switching another new picture will show the original picture of the multiplexed control. Can this transitional effect be optimized?
2. When accessing permissions, choose not to allow, jump to set the interface, do not set the opening, return project will crash.
3. Donot change titleColor
4, After selecting the photo, the bottom toolbar adapts to the problem.

**Comment by ray00178** [comment]
@hanjunqiang 
Thank u ur suggestions. 
The second, I will be fix on next version. Then the first and third, I need think How to do, is the best way.

**Comment by hanjunqiang** [comment]
ok
