### ISSUE TITLE
There is an adaptation problem on non-profiled screens such as iPhone 8.

### ISSUE THREAD

**Issue by YujxZJCN** [ray00178/EasyAlbum#2]
When I use the EasyAlbum on iPhone 6s, the bottom of the view doesn't look so refined. It is the same on iPhone 8.
Please see the photo.
![Simulator Screen Shot - iPhone 6s - 2019-08-18 at 19 00 08](https://user-images.githubusercontent.com/46392855/63223804-8f791d80-c1ed-11e9-9290-0521c82f1d76.png)

**Comment by ray00178** [comment]
@YujxZJCN 
I got it. This's bug, will be fix on next version. Thank you your feedback.
